controller:
    serviceType: ClusterIP
    servicePort: 80
    admin:
        password: password
    # image:
    #     registry: 'docker.io'
    #     repository: 'moaaz6briek/jenkins-with-pipelines'
    #     tag: '1.0.2'
    # installPlugins: false
    # imagePullPolicy: 'Always'

    ingress:
        enabled: true
        ingressClassName: nginx
        annotations:
            kubernetes.io/ingress.class: nginx
            cert-manager.io/cluster-issuer: 'letsencrypt'
        hostName: ${jenkins_host}
        path: /
        tls:
            - hosts:
                  - ${jenkins_host}
              secretName: jenkins-tls
persistence:
    enabled: true
    storageClass: ebs-csi
    size: 3Gi
    accessMode: ReadWriteOnce
